import type { StepConfig } from "./types";

export const STEPS: ReadonlyArray<StepConfig> = [
  {
    id: "entrance",
    index: 0,
    character: { emotion: "happy", region: "center" },
    speech:
      "안녕하세요. 저는 토마토에요 🍅\n레시피 저장소에 오신 걸 환영합니다.\n잠깐 같이 둘러볼까요?",
    trigger: { type: "auto", delayMs: 2600 },
    blocksTouches: true,
  },
  {
    id: "tap-fab",
    index: 1,
    anchorId: "fab-add-ingredient",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech: "이 버튼을 눌러서\n재료를 추가해 볼까요?",
    trigger: { type: "tap-anchor", anchorId: "fab-add-ingredient" },
    spotlightShape: "circle",
    blocksTouches: true,
  },
  {
    id: "picker-intro",
    index: 2,
    anchorId: "picker-categories",
    character: { emotion: "pointing", region: "center" },
    speech: "재료 추가 화면이에요!\n카테고리로 종류별로 볼 수 있어요.",
    trigger: { type: "auto", delayMs: 3000 },
    advanceOnSegment: "(fridge)",
    spotlightPadding: 2,
    spotlightHorizontalInset: 16,
    blocksTouches: false,
  },
  {
    id: "picker-pick",
    index: 3,
    anchorId: "picker-ingredient-first",
    character: { emotion: "taunting", region: "beside-anchor" },
    speech: "먼저 이 재료를\n눌러 보세요!",
    trigger: { type: "progress", key: "picker-picked-1" },
    advanceOnSegment: "(fridge)",
    spotlightShape: "circle",
    blocksTouches: true,
  },
  {
    id: "picker-pick-next",
    index: 4,
    anchorId: "picker-ingredient-second",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech: "좋아요!\n이번엔 이 재료를 선택해 볼까요?",
    trigger: { type: "progress", key: "picker-picked-2" },
    advanceOnSegment: "(fridge)",
    spotlightShape: "circle",
    blocksTouches: true,
  },
  {
    id: "picker-custom",
    index: 5,
    anchorId: "picker-custom",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech: "MY 버튼에서\n원하는 재료를 직접 등록할 수도 있어요!",
    trigger: { type: "auto-or-tap", delayMs: 2800 },
    advanceOnSegment: "(fridge)",
    blocksTouches: true,
  },
  {
    id: "picker-confirm",
    index: 6,
    anchorId: "picker-cta",
    character: { emotion: "pointing", region: "center" },
    speech: "이제 '담기' 버튼을 눌러서\n냉장고에 추가해 볼까요?",
    trigger: { type: "navigation", segmentMatch: "(fridge)" },
    advanceOnSegment: "(basket)",
    blocksTouches: false,
  },
  {
    id: "back-cheer",
    index: 7,
    character: { emotion: "cheering", region: "top-right" },
    speech: "잘했어요!\n이렇게 재료를 관리할 수 있어요.",
    trigger: { type: "auto-or-tap", delayMs: 2400 },
    blocksTouches: true,
  },
  {
    id: "basket-edit-hint",
    index: 8,
    anchorId: "fridge-basket-first-ingredient",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech: "담긴 재료를 누르면\n수량이나 유통기한을 수정할 수 있어요.",
    trigger: { type: "auto-or-tap", delayMs: 3000 },
    spotlightPadding: 2,
    blocksTouches: true,
  },
  {
    id: "fridge-save",
    index: 9,
    anchorId: "fridge-basket-save",
    character: { emotion: "taunting", region: "beside-anchor" },
    speech: "버튼을 눌러서\n내 냉장고에 저장해 볼까요?",
    trigger: { type: "navigation", segmentMatch: "(tabs)" },
    blocksTouches: true,
  },
  {
    id: "recipe-tab-quest",
    index: 10,
    anchorId: "tab-recipe",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech:
      "냉장고에 재료를 담으면\n레시피가 자동으로 추천돼요.\n레시피 저장소로 가볼까요?",
    trigger: { type: "navigation", segmentMatch: "(recipe)" },
    blocksTouches: true,
  },
  {
    id: "search-tab-quest",
    index: 11,
    anchorId: "tab-search",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech: "레시피 검색도 가능해요!",
    trigger: { type: "navigation", segmentMatch: "(search)" },
    blocksTouches: true,
  },
  {
    id: "search-popular-quest",
    index: 12,
    anchorId: "search-popular-keyword",
    character: { emotion: "taunting", region: "beside-anchor" },
    speech: "지금 가장 인기 있는 레시피를\n하나 눌러볼까요?",
    trigger: { type: "progress", key: "search-popular-picked" },
    blocksTouches: true,
  },
  {
    id: "search-result-intro",
    index: 13,
    anchorId: "search-result-source-tabs",
    character: { emotion: "happy", region: "beside-anchor" },
    speech: "블로그, 유튜브, 추천 레시피를\n여기서 한 번에 확인할 수 있어요.",
    trigger: { type: "auto-or-tap", delayMs: 3300 },
    spotlightPadding: 2,
    spotlightHorizontalInset: 12,
    blocksTouches: true,
  },
  {
    id: "my-tab-quest",
    index: 14,
    anchorId: "tab-myPage",
    character: { emotion: "pointing", region: "beside-anchor" },
    speech: "마지막으로 MY 탭도\n둘러볼까요?",
    trigger: { type: "navigation", segmentMatch: "(myPage)" },
    blocksTouches: true,
  },
  {
    id: "my-page-intro",
    index: 15,
    anchorId: "my-recipe-create",
    character: { emotion: "cheering", region: "beside-anchor" },
    speech: "여기서 나만의 레시피를 만들고\n다른 유저와 공유할 수도 있어요.",
    trigger: { type: "auto-or-tap", delayMs: 3300 },
    spotlightShape: "circle",
    blocksTouches: true,
  },
  {
    id: "celebration",
    index: 16,
    character: { emotion: "celebrating", region: "center" },
    speech: "앞으로 잘 부탁드려요!",
    trigger: { type: "auto", delayMs: 2300 },
    blocksTouches: true,
  },
];

export const TOTAL_STEPS = STEPS.length;
